services:
  db:
    image: postgres:15-alpine
    container_name: practice4-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 15
    networks:
      - movie-net

  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practice4-web-app
    environment:
      APP_PORT: "8080"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - movie-net

volumes:
  db_data:

# BONUS (ADVANCED): custom network name
networks:
  movie-net:
    driver: bridge
